language: erlang

script: rebar3 update && rebar3 eunit && rebar3 dialyzer

notifications:
  disabled: true

otp_release:
  - 18.2
  - 19.1
  - 20.1
  - 21.0

cache:
  directories:
  - $HOME/.cache/rebar3/

