language: erlang

install: wget https://github.com/erlang/rebar3/releases/download/3.1.0/rebar3 && chmod 755 rebar3

script: PATH=.:$PATH make update test dialyzer

notifications:
  disabled: true

otp_release:
  - 18.2
  - 19.1
  - 20.1
  - 21.0

cache:
  directories:
  - $HOME/.cache/rebar3/

